config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users

  root "users#show"

  resources :doctors

  resources :users do
    resources :appointments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :doctor

  def summary
    "#{self.month} #{self.day} at #{self.time}"
  end

end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments, dependent: :destroy
  has_many :users, through: :appointments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :appointments, dependent: :destroy
  has_many :doctors, through: :appointments

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_user
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  def index
    
  end

  def show
  end

  def new
    @doctors = Doctor.all
    @appointment = @user.appointments.new
  end

  def create
    @appointment = @user.appointments.new(appointment_params)

    if @appointment.save
      redirect_to user_path(@user)
    else
      render :new
    end

  end

  def edit
    @doctors = Doctor.all
  end

  def update

    if @appointment.update(appointment_params)
      redirect_to user_appointment_path(@user, @appointment)
    else
      render :edit
    end

  end

  def destroy
    @appointment.destroy
    redirect_to user_path(@user)
  end

  private

    def set_user
      @user = current_user
    end

    def set_appointment
      @appointment = @user.appointments.find(params[:id])
    end

    def appointment_params
      params.require(:appointment).permit(:month, :day, :time, :doctor_id)
    end

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  def index
    @doctors = Doctor.all
  end

  def show
    @appointments = @doctor.appointments
    @users = @doctor.users
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)

    if @doctor.save
      redirect_to doctors_path
    else
      render :new
    end

  end

  def edit

  end

  def update
    
    if @doctor.update(doctor_params)
      redirect_to doctor_path(@doctor)
    else
      render :edit
    end

  end

  def destroy
    @doctor.destroy
    redirect_to doctors_path
  end

  private

    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    def doctor_params
      params.require(:doctor).permit(:name)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @appointments = current_user.appointments
    @user = current_user
    @doctors = @user.doctors
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model: [@user, @appointment], local: true) do |f| %>
  
  <div class="field">
    <%= f.label :doctor %>
    <%= f.select :doctor_id, @doctors.collect { |d| [d.name, d.id] } %>
  </div>

  <div class="field">
    <%= f.label :month %>
    <%= f.select :month, ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] %>
  </div>

  <div class="field">
    <%= f.label :day %>
    <%= f.text_field :day, required: true, placeholder: "Day" %>
  </div>

  <div class="field">
    <%= f.label :time %>
    <%= f.text_field :time, required: true, placeholder: "Time" %>
  </div>

  <%= f.submit %>

<% end %>

app/views/appointments/edit.html.erb
<h1>Edit Appointment</h1>
<hr />
<%= render 'form' %>
<br />
<%= link_to "Back", user_appointment_path(@user, @appointment) %>

app/views/appointments/index.html.erb
<h1>Appointments#index</h1>
<p>Find me in app/views/appointments/index.html.erb</p>

app/views/appointments/new.html.erb
<h1>Create Appointment</h1>
<hr />
<%= render 'form' %>

app/views/appointments/show.html.erb
<h1><%= @appointment.summary %></h1>
<hr />
<%= link_to "Edit", edit_user_appointment_path(@user, @appointment) %>
<%= link_to "Cancel", user_appointment_path(@user, @appointment), method: :delete %>

app/views/doctors/_form.html.erb
<%= form_with(model: @doctor, local: true) do |f| %>
  
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, autofocus: true, placeholder: "Name" %>
  </div>

  <%= f.submit %>

<% end %>

app/views/doctors/edit.html.erb
<h1>Edit Doctor</h1>
<hr />

<%= render 'form' %>
<br />
<%= link_to "Back", doctor_path(@doctor) %>

app/views/doctors/index.html.erb
<h1>Doctors</h1>
<hr />

<div class="ui secondary menu">
  <%= link_to "Add Doctor", new_doctor_path, class: "item" %>
</div>

<ul>
  <% @doctors.each do |doctor| %>
    <li>
      <%= link_to doctor.name, doctor_path(doctor) %>
    </li>
  <% end %>
</ul>

app/views/doctors/new.html.erb
<h1>Add Doctor</h1>
<hr />

<%= render 'form' %>

app/views/doctors/show.html.erb
<h1><%= @doctor.name %></h1>
<hr />

<ul>
  <% @appointments.each do |appointment| %>
    <li>
      <%= "#{appointment.summary} with #{@users.find(appointment.user_id).first_name}" %>
    </li>
  <% end %>
</ul>
<div class="ui secondary menu">
  <%= link_to "Edit", edit_doctor_path(@doctor), class: "item" %>
  <%= link_to "Delete", doctor_path(@doctor), method: :delete, class: "item" %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="ui secondary menu">
  <div class="right menu">
    <% if current_user %>
      <%= link_to "Home", user_path(current_user), class: "item" %>
      <%= link_to "View Doctors", doctors_path, class: "item" %>
      <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "item" %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorsAppointmentApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="ui container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/show.html.erb
<h1><%= "Welcome #{@user.full_name}" %></h1>
<hr />
<%= link_to "Create New Appointment", new_user_appointment_path(@user)%>
<br />
<h2><%= @user.appointments.length <= 0 ? "No Appointments" : "Appointments" %></h2>
<ul>
  <% @appointments.each do |appointment| %>
    <li>
      <%= link_to "#{appointment.summary} with #{@doctors.find(appointment.doctor_id).name}", user_appointment_path(@user, appointment) %>
    </li>
  <% end %>
</ul>